name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  pretest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: install dependencies
      run: |
        pip install pygithub

    - name: run help
      run: |
        ./backport.py --help

    - name: install dev dependencies
      run: |
        pip install mypy

    - name: mypy
      run: |
        mypy .
